"""Generate combined parse report with explanations."""
import json
import os

lines = []

def hr():
    lines.append("=" * 90)

def section(title):
    lines.append("")
    hr()
    lines.append(f"  {title}")
    hr()
    lines.append("")

# ── HEADER ──
hr()
lines.append("  AWS CardDemo Mainframe Application — Complete Parse Report")
lines.append("  Generated by ProLeap COBOL Parser + JCL Parser")
hr()
lines.append("")
lines.append("This report contains the structured output from parsing the AWS CardDemo")
lines.append("mainframe sample application. It demonstrates what a mainframe modernization")
lines.append("tool can extract from legacy COBOL source code and JCL job definitions.")
lines.append("")

# ══════════════════════════════════════════════════════════════════════
# COBOL SECTION
# ══════════════════════════════════════════════════════════════════════
section("PART 1: COBOL PARSER OUTPUT (6 programs)")
lines.append("The COBOL parser extracts the internal structure of each program:")
lines.append("  - program_id      : The PROGRAM-ID from the IDENTIFICATION DIVISION")
lines.append("  - description     : From AUTHOR and REMARKS paragraphs")
lines.append("  - copybooks[]     : COPY statements resolved during preprocessing")
lines.append("  - paragraphs[]    : Procedure division paragraph/section names (the program's functions)")
lines.append("  - calls[]         : Programs invoked via CALL statements (static=literal, dynamic=variable)")
lines.append("  - cics_operations[]: EXEC CICS commands (for online programs)")
lines.append("  - variables[]     : Data items with level number, PIC clause, and USAGE")
lines.append("  - files[]         : File definitions from FILE-CONTROL with open mode")
lines.append("  - io_operations   : READ and WRITE statements referencing files/records")
lines.append("  - summary         : Auto-classified type (batch/online/orchestrator) + data flow + purpose")
lines.append("")

for f in sorted(os.listdir("output-final-cobol")):
    if not f.endswith(".json"):
        continue
    with open(os.path.join("output-final-cobol", f)) as fh:
        d = json.load(fh)

    name = f.replace(".json", "")
    lines.append("-" * 90)
    lines.append(f"COBOL Program: {name}.cbl")
    lines.append(f'  Program ID : {d["program_id"]}')

    # Description
    desc = d.get("description", "")
    if desc:
        # Truncate long descriptions to first meaningful sentence
        short_desc = desc.split(".")[0].strip() if len(desc) > 120 else desc.strip()
        if len(desc) > 120:
            short_desc += "..."
        lines.append(f"  Description: {short_desc}")

    # Summary / Classification
    summary = d.get("summary", {})
    if summary:
        lines.append(f'  Type       : {summary.get("type", "")}')
        lines.append(f'  Purpose    : {summary.get("purpose", "")}')

    # Copybooks
    copybooks = d.get("copybooks", [])
    if copybooks:
        unique_cpy = list(dict.fromkeys(copybooks))  # deduplicate preserving order
        lines.append(f'  Copybooks  : {", ".join(unique_cpy)}')

    # Paragraphs
    paragraphs = d.get("paragraphs", [])
    if paragraphs:
        if len(paragraphs) > 8:
            shown_paras = ", ".join(paragraphs[:8]) + f" ... ({len(paragraphs)} total)"
        else:
            shown_paras = ", ".join(paragraphs)
        lines.append(f"  Paragraphs : {shown_paras}")

    # Calls
    calls = d.get("calls", [])
    if calls:
        progs = ", ".join(f'{c["program"]} ({c["type"]})' for c in calls)
        lines.append(f"  Calls      : {progs}")
    else:
        lines.append(f"  Calls      : (none)")

    # CICS Operations
    cics = d.get("cics_operations", [])
    if cics:
        lines.append(f"  CICS Ops   : {len(cics)} EXEC CICS commands")
        for op in cics[:5]:
            # Shorten for display
            short_op = op.replace("EXEC CICS ", "").replace(" END-EXEC", "")
            lines.append(f"               - {short_op}")
        if len(cics) > 5:
            lines.append(f"               ... and {len(cics) - 5} more")

    # Variables summary
    vars_list = d.get("variables", [])
    total_vars = len(vars_list)
    pic_vars = [v for v in vars_list if v.get("pic")]
    group_vars = [v for v in vars_list if not v.get("pic") and v.get("level") != 88]
    level88 = [v for v in vars_list if v.get("level") == 88]
    lines.append(
        f"  Variables  : {total_vars} total "
        f"({len(pic_vars)} elementary, {len(group_vars)} group, {len(level88)} condition names)"
    )

    # Show first few interesting variables
    shown = 0
    for v in vars_list:
        if v.get("pic") and v.get("name") and shown < 5:
            usage = f', USAGE {v["usage"]}' if v.get("usage") else ""
            lines.append(f'               {v["level"]:02d} {v["name"]:30s} PIC {v["pic"]}{usage}')
            shown += 1
    if total_vars > 5:
        lines.append(f"               ... and {total_vars - 5} more")

    # Files
    files = d.get("files", [])
    if files:
        for fi in files:
            lines.append(f'  File       : {fi["file_name"]:25s} mode={fi["mode"]}')
    else:
        lines.append(f"  Files      : (none - CICS program uses VSAM via EXEC CICS)")

    # I/O
    io = d.get("io_operations", {})
    reads = io.get("reads", [])
    writes = io.get("writes", [])
    if reads:
        lines.append(f'  Reads      : {", ".join(reads)}')
    if writes:
        lines.append(f'  Writes     : {", ".join(writes)}')
    lines.append("")

# Explanation
lines.append("")
lines.append("WHAT THIS MEANS:")
lines.append("  Each COBOL program is a standalone unit of business logic on the mainframe.")
lines.append("  - CBACT01C reads account data from a VSAM file and writes it to multiple")
lines.append("    output formats (fixed, array, variable-length). It calls COBDATFT for")
lines.append("    date formatting and CEE3ABD for abnormal termination handling.")
lines.append("  - CBACT03C reads card cross-reference data (card# -> customer -> account).")
lines.append("  - CBSTM03A generates customer statements by reading transactions, accounts,")
lines.append("    customers, and cross-references, then writing text + HTML statement files.")
lines.append("    It calls CBSTM03B 13 times for file I/O operations.")
lines.append("  - COACTUPC is a CICS online program for updating account details on screen.")
lines.append("    It has no file I/O - CICS programs access VSAM via EXEC CICS commands.")
lines.append("  - COSGN00C is the CICS sign-on screen - handles user authentication.")
lines.append("  - COTRN01C is the CICS transaction list screen - displays transactions.")
lines.append("")

# ══════════════════════════════════════════════════════════════════════
# JCL SECTION
# ══════════════════════════════════════════════════════════════════════
section("PART 2: JCL PARSER OUTPUT (47 jobs)")
lines.append("The JCL parser extracts the execution structure of each batch job:")
lines.append("  - job_name       : The JOB card name")
lines.append("  - steps[]        : Each EXEC statement becomes a step")
lines.append("  - step.program   : The program or utility being executed")
lines.append("  - step.datasets[]: DD statements with dataset name, type, and disposition")
lines.append("    type = input  : DISP=SHR or DISP=OLD (reading existing data)")
lines.append("    type = output : DISP=NEW or DISP=MOD (creating/appending data)")
lines.append("    type = temp   : DISP=(MOD,DELETE,DELETE) or &&prefix (scratch space)")
lines.append("  - step.cond      : Conditional execution (e.g., skip if prior step failed)")
lines.append("  - step.parm      : Parameters passed to the program")
lines.append("")

for f in sorted(os.listdir("output-final-jcl")):
    if not f.endswith(".json"):
        continue
    with open(os.path.join("output-final-jcl", f)) as fh:
        d = json.load(fh)

    name = f.replace(".json", "")
    steps = d.get("steps", [])
    programs = [s["program"] for s in steps]

    lines.append("-" * 90)
    lines.append(f"JCL Job: {name}")
    lines.append(f'  Job Name : {d["job_name"]}')
    lines.append(f"  Steps    : {len(steps)}")
    lines.append(f'  Programs : {", ".join(programs)}')

    for s in steps:
        cond = f'  COND={s["cond"]}' if s.get("cond") else ""
        parm = f'  PARM={s["parm"]}' if s.get("parm") else ""
        lines.append(f'    Step {s["step_name"]:12s} -> {s["program"]:12s}{cond}{parm}')
        for ds in s.get("datasets", []):
            lines.append(f'      {ds["type"]:6s}  {ds["dsn"]}  DISP={ds["disp"]}')
    lines.append("")

# Explanation
lines.append("")
lines.append("WHAT THIS MEANS:")
lines.append("  JCL defines HOW and WHEN COBOL programs run on the mainframe.")
lines.append("  Each JCL job is a batch execution unit - it runs one or more steps in sequence.")
lines.append("")
lines.append("  Key patterns in this application:")
lines.append("  - IDCAMS jobs (ACCTFILE, CARDFILE, CUSTFILE, XREFFILE, etc.) manage VSAM datasets:")
lines.append("    they DELETE old clusters, DEFINE new ones, and REPRO (copy) data into them.")
lines.append('    These are the "database setup" jobs.')
lines.append("")
lines.append("  - Business processing jobs run COBOL programs:")
lines.append("    POSTTRAN  -> CBTRN02C  (post daily transactions)")
lines.append("    INTCALC   -> CBACT04C  (calculate interest)")
lines.append("    CREASTMT  -> CBSTM03A  (generate customer statements)")
lines.append("    READACCT  -> CBACT01C  (extract account data)")
lines.append("    CBEXPORT  -> CBEXPORT  (export all data)")
lines.append("")
lines.append("  - Utility jobs use system programs:")
lines.append("    SORT      -> sort/merge transaction files")
lines.append("    IEFBR14   -> dummy program for dataset allocation/deletion")
lines.append("    SDSF      -> open/close files in CICS")
lines.append("")
lines.append("  - Compile jobs (BATCMP, CICCMP, etc.) use PROCs to compile COBOL source.")
lines.append("")
lines.append("  - The COND parameter controls step execution:")
lines.append('    COND=(0,NE) means "skip this step if any prior step returned RC != 0"')
lines.append("    This creates a pipeline where later steps only run if earlier ones succeeded.")
lines.append("")

# ── CROSS-REFERENCE ──
section("PART 3: CROSS-REFERENCE - How JCL Jobs Invoke COBOL Programs")
lines.append("This shows which JCL jobs execute which COBOL programs,")
lines.append("and what data flows between them.")
lines.append("")

# Load COBOL programs
cobol_programs = {}
for f in sorted(os.listdir("output-final-cobol")):
    if not f.endswith(".json"):
        continue
    with open(os.path.join("output-final-cobol", f)) as fh:
        d = json.load(fh)
    cobol_programs[d["program_id"]] = d

# Find JCL->COBOL links
for f in sorted(os.listdir("output-final-jcl")):
    if not f.endswith(".json"):
        continue
    with open(os.path.join("output-final-jcl", f)) as fh:
        d = json.load(fh)
    for s in d.get("steps", []):
        pgm = s["program"]
        if pgm in cobol_programs:
            cp = cobol_programs[pgm]
            ds_in = [
                ds["dsn"]
                for ds in s.get("datasets", [])
                if ds["type"] == "input" and "LOADLIB" not in ds["dsn"]
            ]
            ds_out = [
                ds["dsn"]
                for ds in s.get("datasets", [])
                if ds["type"] == "output"
            ]
            calls = [c["program"] for c in cp.get("calls", [])]
            summary = cp.get("summary", {})
            prog_type = summary.get("type", "")
            purpose = summary.get("purpose", "")
            copybooks_used = list(dict.fromkeys(cp.get("copybooks", [])))

            lines.append(
                f'  JCL {d["job_name"]:12s} step {s["step_name"]:10s} -> COBOL {pgm}  [{prog_type}]'
            )
            if purpose:
                lines.append(f'    Purpose  : {purpose}')
            if ds_in:
                lines.append(f'    Reads    : {", ".join(ds_in)}')
            if ds_out:
                lines.append(f'    Writes   : {", ".join(ds_out)}')
            if calls:
                lines.append(f'    Calls    : {", ".join(calls)}')
            if copybooks_used:
                lines.append(f'    Copybooks: {", ".join(copybooks_used[:10])}{"..." if len(copybooks_used) > 10 else ""}')
            lines.append("")

lines.append("")
lines.append("This cross-reference is the foundation for mainframe modernization:")
lines.append("it maps the full data flow from JCL batch scheduling through COBOL")
lines.append("business logic to the datasets (files/databases) that hold the data.")
lines.append("")
hr()
lines.append("  End of Report")
hr()

report = "\n".join(lines)
with open("parse_report.txt", "w") as f:
    f.write(report)

print(f"Report written to: parse_report.txt ({len(report)} chars, {len(lines)} lines)")
